### ISSUE TITLE
lmdb image read problem

### ISSUE THREAD

**Issue by hxngiee** [wpeebles/gangealing#8]
Thanks for your great work

To run the vis_correspondence.py, 
I setup this repo and preparing real data(LSUN cat) but the following error appear

```
Traceback (most recent call last):
  File "applications/propagate_to_images.py", line 154, in <module>
    make_visuals(args, t_ema, classifier)
  File "/home/ubuntu/anaconda3/envs/ugatit/lib/python3.8/site-packages/torch/autograd
/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "applications/propagate_to_images.py", line 49, in make_visuals
    sample_images_and_points(args, t, classifier, device='cuda')
  File "/home/ubuntu/anaconda3/envs/ugatit/lib/python3.8/site-packages/torch/autograd
/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/data/hongiee/gangealing/applications/vis_correspondence.py", line 34, in sam
ple_images_and_points
 dset = MultiResolutionDataset(args.real_data_path, resolution=args.real_size)
  File "/data/hongiee/gangealing/datasets/dataset.py", line 28, in __init__
    self.length = int(txn.get('length'.encode('utf-8')).decode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'decode'
```
how can I solve this problem?

**Comment by WestbrookZero** [comment]
@hxngiee I have the same problem. How did you solve it？
